# For more options, use the src/GNUmakefile
# DESTDIR, if defined, comes from rpmbuild and is the directory for the
# temporary build.

# These are substituted by configure
#
MAKE=GMAKETYPE
PREFIX=PREFIXSUB
MANPREFIX=MANPREFIXSUB

all:
	$(MAKE) -C src

clean:
	$(MAKE) clean -C src

distclean:
	$(MAKE) distclean -C src

test:
	$(MAKE) test -C src

max:
	$(MAKE) -C src max

install:
ifdef RPM_BUILD_ROOT
	install -d ${DESTDIR}${PREFIX}/bin
	install -m 555 src/spar ${DESTDIR}${PREFIX}/bin/spar
	install -d ${DESTDIR}$(MANPREFIX)/man1
	install -m 555 src/spar.1 ${DESTDIR}${MANPREFIX}/man1/spar.1
else
	install -d ${PREFIX}/bin
	install -m 555 src/spar ${PREFIX}/bin/spar
	install -d $(MANPREFIX)/man/man1
	install -m 555 src/spar.1 ${MANPREFIX}/man/man1/spar.1
endif

uninstall:
ifdef RPM_BUILD_ROOT
	rm ${DESTDIR}/${PREFIX}/bin/spar
	rm ${DESTDIR}/${MANPREFIX}/man1/spar.1
else
	rm ${PREFIX}/bin/spar
	rm ${MANPREFIX}/man/man1/spar.1
endif

help:
	@echo "Try make, make install or make uninstall"
	@echo "If you have the sources, there are more options"
	@echo "in the src directory"

.PHONY: all clean distclean test max install uninstall help

